"""empty message

Revision ID: 9527f3560944
Revises: 35c031e86809
Create Date: 2024-07-20 07:35:33.156080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9527f3560944'
down_revision = '35c031e86809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_character_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('user_favorite_character_favorite_people_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'character', ['favorite_character_id'], ['id'])
        batch_op.drop_column('favorite_people_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_people_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_favorite_character_favorite_people_id_fkey', 'character', ['favorite_people_id'], ['id'])
        batch_op.drop_column('favorite_character_id')

    # ### end Alembic commands ###
